export const OPTIMIZER_CONFIG = Symbol("OPTIMIZER_CONFIG");
export const OPTIMIZER_USE_CASE = Symbol("OPTIMIZER_USE_CASE");
export const OPTIMIZER_EMBEDDING_CLIENT = Symbol("OPTIMIZER_EMBEDDING_CLIENT");
export const OPTIMIZER_CACHE_STORE = Symbol("OPTIMIZER_CACHE_STORE");
export const OPTIMIZER_SKILL_STORE = Symbol("OPTIMIZER_SKILL_STORE");
export const OPTIMIZER_VECTOR_STORE = Symbol("OPTIMIZER_VECTOR_STORE");
export const OPTIMIZER_LLM_CLIENT = Symbol("OPTIMIZER_LLM_CLIENT");
export const OPTIMIZER_TELEMETRY = Symbol("OPTIMIZER_TELEMETRY");
